import 'package:flutter/material.dart';
import 'package:filter_list/filter_list.dart';

class MusicalInterestsInput extends StatefulWidget {
  const MusicalInterestsInput({
    Key? key,
    required this.updateFunc,
    required this.formKey,
    required this.listInterests,
  }) : super(key: key);
  final Function(List<String> data) updateFunc;
  final List<String> listInterests;

  final Key formKey;
  @override
  _BirthInputState createState() => _BirthInputState();
}

class _BirthInputState extends State<MusicalInterestsInput> {
  final TextEditingController _formBirthFieldControllerKey =
      TextEditingController();

  final FocusNode _formBirthFieldNode = FocusNode();

  void _openFilterDialog() async {
    await FilterListDialog.display<String>(
      context,
      listData: listMusicGenre,
      selectedListData: widget.listInterests,
      height: 480,
      headlineText: "Which music do you like?",
      searchFieldHintText: "Search Here",
      choiceChipLabel: (item) {
        return item;
      },
      validateSelectedItem: (list, val) {
        return list!.contains(val);
      },
      onItemSearch: (list, text) {
        if (list!.any(
            (element) => element.toLowerCase().contains(text.toLowerCase()))) {
          return list
              .where((element) =>
                  element.toLowerCase().contains(text.toLowerCase()))
              .toList();
        } else {
          return [];
        }
      },
      controlContainerDecoration: BoxDecoration(
          color: Colors.grey.shade800, borderRadius: BorderRadius.circular(30)),
      closeIconColor: Colors.grey.shade700,
      applyButonTextBackgroundColor: Colors.grey.shade900,
      searchFieldBackgroundColor: Colors.grey.shade400,
      unselectedTextbackGroundColor: Colors.grey.shade500,
      backgroundColor: Colors.black54,
      onApplyButtonClick: (list) {
        if (list != null) {
          widget.updateFunc(list);
        }
        Navigator.pop(context);
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 8.0),
      child: Container(
        width: 280,
        child: Form(
          autovalidateMode: AutovalidateMode.onUserInteraction,
          child: TextFormField(
            minLines: 1,
            maxLines: 8,
            readOnly: true,
            key: widget.formKey,
            controller: _formBirthFieldControllerKey
              ..text = widget.listInterests.join(', '),
            focusNode: _formBirthFieldNode,
            onTap: () {
              _formBirthFieldNode.unfocus();
              _openFilterDialog();
            },
            decoration: InputDecoration(
              alignLabelWithHint: true,
              border: OutlineInputBorder(
                borderRadius: const BorderRadius.all(
                  Radius.circular(30.0),
                ),
                borderSide: BorderSide.none,
              ),
              enabledBorder: OutlineInputBorder(
                borderRadius: const BorderRadius.all(
                  Radius.circular(30.0),
                ),
                borderSide: BorderSide.none,
              ),
              focusedBorder: OutlineInputBorder(
                borderRadius: const BorderRadius.all(
                  Radius.circular(30.0),
                ),
                borderSide: BorderSide(color: Colors.grey.shade700, width: 1.0),
              ),
              filled: true,
              contentPadding: EdgeInsets.fromLTRB(25, 0, 5, 0),
              fillColor: Colors.black26,
              labelStyle: TextStyle(color: Colors.white),
              errorStyle: TextStyle(
                  fontStyle: FontStyle.italic, fontWeight: FontWeight.w400),
              labelText: 'Musical interests',
            ),
            style: TextStyle(color: Colors.white),
          ),
        ),
      ),
    );
  }
}

const List<String> listMusicGenre = [
  "Alternative",
  "Adult Alternative",
  "Britpop",
  "Classic Alternative",
  "College",
  "Dancepunk",
  "Dream Pop",
  "Emo",
  "Goth",
  "Grunge",
  "Indie Pop",
  "Indie Rock",
  "Industrial",
  "Lo-Fi",
  "Modern Rock",
  "New Wave",
  "Noise Pop",
  "Post-Punk",
  "Power Pop",
  "Punk",
  "Ska",
  "Xtreme",
  "Blues",
  "Acoustic Blues",
  "Chicago Blues",
  "Contemporary Blues",
  "Country Blues",
  "Delta Blues",
  "Electric Blues",
  "Cajun/Zydeco",
  "Classical",
  "Baroque",
  "Chamber",
  "Choral",
  "Classical Period",
  "Early Classical",
  "Impressionist",
  "Modern",
  "Opera",
  "Piano",
  "Romantic",
  "Symphony",
  "Country",
  "Alt-Country",
  "Americana",
  "Bluegrass",
  "Classic Country",
  "Contemporary Bluegrass",
  "Contemporary Country",
  "Honky Tonk",
  "Hot Country Hits",
  "Western",
  "Easy Listening",
  "Exotica",
  "Light Rock",
  "Lounge",
  "Orchestral Pop",
  "Polka",
  "Space Age Pop",
  "Electronic",
  "Acid House",
  "Ambient",
  "Big Beat",
  "Breakbeat",
  "Dance",
  "Demo",
  "Disco",
  "Downtempo",
  "Drum and Bass",
  "Electro",
  "Garage",
  "Hard House",
  "House",
  "IDM",
  "Remixes",
  "Jungle",
  "Progressive",
  "Techno",
  "Trance",
  "Tribal",
  "Trip Hop",
  "Folk",
  "Alternative Folk",
  "Contemporary Folk",
  "Folk Rock",
  "New Acoustic",
  "Traditional Folk",
  "World Folk",
  "Themes",
  "Adult",
  "Best Of",
  "Chill",
  "Experimental",
  "Female",
  "Heartache",
  "LGBT",
  "Love/Romance",
  "Party Mix",
  "Patriotic",
  "Rainy Day Mix",
  "Reality",
  "Sexy",
  "Shuffle",
  "Travel Mix",
  "Tribute",
  "Trippy",
  "Work Mix",
  "Rap",
  "Alternative Rap",
  "Dirty South",
  "East Coast Rap",
  "Freestyle",
  "Hip Hop",
  "Gangsta Rap",
  "Mixtapes",
  "Old School",
  "Turntablism",
  "Underground Hip-Hop",
  "West Coast Rap",
  "Inspirational",
  "Christian",
  "Christian Metal",
  "Christian Rap",
  "Christian Rock",
  "Classic Christian",
  "Contemporary Gospel",
  "Gospel",
  "Praise/Worship",
  "Sermons/Services",
  "Southern Gospel",
  "Traditional Gospel",
  "International",
  "African",
  "Afrikaans",
  "Arabic",
  "Asian",
  "Brazilian",
  "Caribbean",
  "Celtic",
  "European",
  "Filipino",
  "Greek",
  "Hawaiian/Pacific",
  "Hindi",
  "Indian",
  "Japanese",
  "Jewish",
  "Klezmer",
  "Mediterranean",
  "Middle Eastern",
  "North American",
  "Polskie",
  "Polska",
  "Soca",
  "South American",
  "Tamil",
  "Worldbeat",
  "Zouk",
  "Jazz",
  "Acid Jazz",
  "Avant Garde",
  "Big Band",
  "Bop",
  "Classic Jazz",
  "Cool Jazz",
  "Fusion",
  "Hard Bop",
  "Latin Jazz",
  "Smooth Jazz",
  "Swing",
  "Vocal Jazz",
  "World Fusion",
  "Latin",
  "Bachata",
  "Banda",
  "Bossa Nova",
  "Cumbia",
  "Latin Dance",
  "Latin Pop",
  "Latin Rap/Hip-Hop",
  "Latin Rock",
  "Mariachi",
  "Merengue",
  "Ranchera",
  "Reggaeton",
  "Regional Mexican",
  "Salsa",
  "Tango",
  "Tejano",
  "Tropicalia",
  "Metal",
  "Black Metal",
  "Classic Metal",
  "Extreme Metal",
  "Grindcore",
  "Hair Metal",
  "Heavy Metal",
  "Metalcore",
  "Power Metal",
  "Progressive Metal",
  "Rap Metal",
  "New Age",
  "Environmental",
  "Ethnic Fusion",
  "Healing",
  "Meditation",
  "Spiritual",
  "30s",
  "40s",
  "50s",
  "60s",
  "70s",
  "80s",
  "90s",
  "Pop",
  "Adult Contemporary",
  "Barbershop",
  "Bubblegum Pop",
  "Dance Pop",
  "Idols",
  "Oldies",
  "JPOP",
  "Soft Rock",
  "Teen Pop",
  "Top 40",
  "World Pop",
  "R&B/Urban",
  "Classic R&B",
  "Contemporary R&B",
  "Doo Wop",
  "Funk",
  "Motown",
  "Neo-Soul",
  "Quiet Storm",
  "Soul",
  "Urban Contemporary",
  "Reggae",
  "Contemporary Reggae",
  "Dancehall",
  "Dub",
  "Pop-Reggae",
  "Ragga",
  "Rock Steady",
  "Reggae Roots",
  "Rock",
  "Adult Album Alternative",
  "British Invasion",
  "Classic Rock",
  "Garage Rock",
  "Glam",
  "Hard Rock",
  "Jam Bands",
  "Piano Rock",
  "Prog Rock",
  "Psychedelic",
  "Rock & Roll",
  "Rockabilly",
  "Singer/Songwriter",
  "Surf",
  "Seasonal/Holiday",
  "Anniversary",
  "Birthday",
  "Christmas",
  "Halloween",
  "Hanukkah",
  "Honeymoon",
  "Valentine",
  "Wedding",
  "Winter",
  "Soundtracks",
  "Anime",
  "Bollywood",
  "Kids",
  "Original Score",
  "Showtunes",
  "Video Game Music",
  "Talk",
  "Comedy",
  "Community",
  "Educational",
  "Government",
  "News",
  "Old Time Radio",
  "Other Talk",
  "Political",
  "Public Radio",
  "Scanner",
  "Spoken Word",
  "Sports",
  "Technology",
  "Hardcore",
  "Eclectic",
  "Instrumental",
];
